<div class="px-4 py-3 border rounded-lg" role="alert" style="border-color: rgba(var(--primary-500));">
    <div class="flex items-center">
        <x-filament::icon icon="heroicon-s-information-circle" class="flex-shrink-0 w-6 h-6" style="color: rgba(var(--primary-500));" />

        <div class="text-sm px-4">
            {!! str('If you need `timestamps`, you\'ll need to set them up manually. They are not generated by default.')->inlineMarkdown()->toHtmlString() !!}
        </div>
    </div>
</div>